system:
    debug: false
    error_reporting: 0
    mode: prod
    timezone: 'UTC'
    secret: 'This-token-is-not-safe'
error:
    template: windwalker.error.default
session:
    handler: native
    expire_time: 15
routing:
    debug: 1
    simple_route: true
cache:
    enabled: false
    storage: file
    handler: serialize
    dir: cache
    time: 15
language:
    debug: false
    locale: en-GB
    default: en-GB
    format: ini
    path: resources/languages
console:
    script: ~
