system:
    debug: 1
    timezone: 'UTC'
database:
    driver: mysql
    host: localhost
    user: root
    password: '1234'
    name: acme
    prefix: wind_
language:
    debug: 0
    locale: en-GB
    default: en-GB
    format: ini
    path: resources/languages
