home:
  pattern: '/'
  variables:
    _controller: 'Acme\Controller\Page\'
page:
  pattern: 'page'
  variables:
      _controller: 'Acme\Controller\Page\'
cover:
  pattern: 'cover'
  variables:
      _controller: 'Acme\Controller\Cover\'
user:
  pattern: '/'
  package: wwuser
