login:
    pattern: login
    variables:
        _controller: 'Windwalker\User\Controller\Login'
logout:
    pattern: logout
    variables:
        _controller: 'Windwalker\User\Controller\Logout'
registration:
    pattern: registration
    variables:
        _controller: 'Windwalker\User\Controller\Register'
