login:
    pattern: login
    controller: 'Windwalker\User\Controller\Login'
    suffix:
        post: 'LoginController'
logout:
    pattern: logout
    variables:
        _controller: 'Windwalker\User\Controller\Logout'
registration:
    pattern: registration
    variables:
        _controller: 'Windwalker\User\Controller\Register'
