login:
    pattern: login
    controller: 'Windwalker\User\Controller\Login'
    action:
        'get': 'IndexController'
        'post': 'LoginController'
logout:
    pattern: logout
    variables:
        _controller: 'Windwalker\User\Controller\Logout'
registration:
    pattern: registration
    variables:
        _controller: 'Windwalker\User\Controller\Register'
