
dashboard:
    pattern: /
    controller: Dashboard

system:
    pattern: /system(/id)
    controller: System

request:
    pattern: /request(/id)
    controller: Request

routing:
    pattern: /routing(/id)
    controller: Routing

timeline:
    pattern: /timeline(/id)
    controller: Timeline

database:
    pattern: /database(/id)
    controller: Database
